Repository Astrodevil/Google-Cloud-Facilitator-Program, pull requests merged in 2021-04, with the labels that each got.

#4 Set up and Configure a Cloud Environment in Google Cloud: Challenge Lab
  Set up and Configure a Cloud Environment in Google Cloud: Challenge Lab.md
Labels: enhancement

#3 Update Insights from Data with BigQuery: Challenge Lab
  Insights from Data with BigQuery Challenge Lab.md
  README.md
Labels: documentation, enhancement, good first issue, help wanted

#2 Perform Foundational Infrastructure Tasks in Google Cloud.md
  Perform Foundational Infrastructure Tasks in Google Cloud.md
Labels: documentation, enhancement, good first issue, help wanted

#1 Deploy to Kubernetes in Google Cloud: Challenge Lab
  Deploy to Kubernetes in Google Cloud: Challenge Lab .md
Labels: enhancement, good first issue, help wanted
